

#mybatis-plus
mybatis-plus:
  # \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/*Mapper.xml

  mapper-locations: classpath:/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.example.demo.entity
  # \u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
  global-config:
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: id_worker
      #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: IGNORED
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      table-underline: true
      #mp2.3+ \u5168\u5C40\u8868\u524D\u7F00 mp_
      #table-prefix: mp_
      #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
      refresh-mapper: true
      #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
      #capital-mode: true
      #\u903B\u8F91\u5220\u9664\u914D\u7F6E\uFF08\u4E0B\u97623\u4E2A\u914D\u7F6E\uFF09
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      db-type: mysql

  # \u539F\u751F\u914D\u7F6E
  configuration:
    #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
    map-underscore-to-camel-case: true
    cache-enabled: false
    #\u914D\u7F6EJdbcTypeForNull, oracle\u6570\u636E\u5E93\u5FC5\u987B\u914D\u7F6E
    jdbc-type-for-null: 'null'



##---JDBC \u914D\u7F6E------
spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/scott?useUnicode=true&characterEncoding=UTF8
      username: root
      password: JuFADZvZIKvrR+TwUPO7vMs5LuYao3+GYwM0HqLZG0BuZ6Sr1/r1mVBAh0w3KTBwsKuYAxJksQNac4Iaahf3rQ==
      driver-class-name: com.mysql.jdbc.Driver
##---\u8FDE\u63A5\u6C60\u914D\u7F6E-----
      initial-size: 1
      max-active: 20
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      connectionProperties: "config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIbRP0HjHCi6kWC4AUHKxiTX2jwYRFvDLvNHp0+K82W5sPF3LVGHL2thyPQ39LgAYpz61xBON1AiIQBKR9t40TUCAwEAAQ=="
      filter:
        config:
          enabled: true